[package]
name = "tmux-knight"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
colored = "3.0.0"
dirs = "6.0.0"
symlink = "0.1.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
